### ISSUE TITLE
BananaPi M3

### ISSUE THREAD

**Issue by aszykm** [LeMaker/RPi.GPIO_BP#8]
Anyone test on BPI-M3, because I have a error that this isn't a RPI ?

RuntimeError: This module can only be run on a Raspberry Pi!

**Comment by PingTrip** [comment]
In ./source/cpuinfo.c there is a check for CPU type that is hardcoded to "sun7i". This needs to match the beginning of the 'Hardware' section in the contents of /proc/cpuinfo. The issue is that different kernels will produce a different hardware value. For example, running Bananian (1508) on my BananaPi produces:

`Hardware   : Allwinner sun7i (A20) Family`

Thus producing the same "_This module can only be run on a Raspberry Pi!_" error that you're seeing.

I made the following change in cpuinfo.c on line 42 and everything works as expected:

`if (strcmp(hardware, "sun7i") == 0 || strcmp(hardware, "Allwinner") == 0) {`

**Comment by Tony-HIT** [comment]
This do not support it.
